import mongoose from 'mongoose';
import { BOOKING_STATUS } from '../utils/constants.js';

// ─── Booking Schema ────────────────────────────────────────────────────────
// Created by Person A's POST /bookings after Person B validates seat locks.
// Person C's webhook handler transitions status to CONFIRMED or FAILED.

const bookingSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },

    event: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Event',
      required: true,
    },

    // Array of seat IDs included in this booking
    seats: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Seat',
        required: true,
      },
    ],

    // Final charged amount in paise — set by Person C's payment service
    // using live price from Person B's pricing engine (never from frontend)
    totalAmount: {
      type: Number,
      default: 0,
    },

    status: {
      type: String,
      enum: Object.values(BOOKING_STATUS),
      default: BOOKING_STATUS.PENDING,
    },

    // Set by Person C after payment creation
    paymentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Payment',
      default: null,
    },

    // UUID v4 generated on client — prevents duplicate bookings on retry
    idempotencyKey: {
      type: String,
      required: true,
      unique: true,
    },

    // Set by Person C's webhook handler on payment_intent.succeeded
    confirmedAt: {
      type: Date,
      default: null,
    },

    cancelledAt: {
      type: Date,
      default: null,
    },

    // Base64 QR code string — generated by Person A after confirmation
    qrCode: {
      type: String,
      default: null,
    },

    // Check-in tracking
    checkedIn: {
      type: Boolean,
      default: false,
    },

    checkedInAt: {
      type: Date,
      default: null,
    },
  },
  { timestamps: true }
);

// ─── Indexes ───────────────────────────────────────────────────────────────

bookingSchema.index({ user: 1, status: 1 });
bookingSchema.index({ event: 1, status: 1 });

export default mongoose.model('Booking', bookingSchema);